
-- URUN ANALIZI  
-- Urunun kodu gelsin, adi gelsin, urunun en dusuk satis fiyati , en yuksek satis fiyati , ort satis fiyati , toplam satis fiyati gelsin  

SELECT 
ITM.ITEMCODE,ITM.ITEMNAME,MIN(OD.UNITPRICE) MINSATIS,MAX(OD.UNITPRICE) MAXSATIS, AVG(OD.UNITPRICE) ORTSATIS, SUM(OD.LINETOTAL) TOPLAMSATIS,SUM(OD.AMOUNT) AS TOPLAMMIKTAR

FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID 

GROUP BY ITM.ITEMCODE, ITM.ITEMNAME