--HER SEHIRDE 1 MAGAZAMIZ VAR VE BU MAGAZALARIN SATIS TUTARINA GORE SIRALAMASI

ALTER VIEW VW_MAGAZA_ANALIZI
AS
SELECT TOP 81
SEHIR, SUM(SATIRTOPLAMI) TOPLAMSATIS

FROM VW_SIPARIS_DETAYLAR

GROUP BY SEHIR
ORDER BY SUM(SATIRTOPLAMI)DESC


SELECT * FROM VW_MAGAZA_ANALIZI