
-- EN COK SATAN 10 URUN KATEGORISINI CEKEN SORGU -->CATEGORY1

-- VIEW KULLANARAK SORGU
SELECT TOP 10 
CATEGORY1, SUM(SATIRTOPLAMI) TOPLAMTUTAR
FROM
VW_SIPARIS_DETAYLAR
GROUP BY CATEGORY1
ORDER BY SUM(SATIRTOPLAMI)DESC

--VIEWSIZ
SELECT TOP 10
ITM.CATEGORY1 KATEGORI2, 
SUM(OD.LINETOTAL) TOPLAMTUTAR
FROM
ITEMS ITM
INNER JOIN ORDERDETAILS OD ON ITM.ID=OD.ITEMID
INNER JOIN ORDERS O ON O.ID= OD.ORDERID

GROUP BY ITM.CATEGORY1
ORDER BY SUM(OD.LINETOTAL) DESC


-- EN COK SATAN 10 URUN KATEGORISINI CEKEN VIEW OLUSTURMA -->CATEGORY1

CREATE VIEW VW_TOP10_KATEGORI
AS
SELECT TOP 10
ITM.CATEGORY1 KATEGORI2, 
SUM(OD.LINETOTAL) TOPLAMTUTAR
FROM
ITEMS ITM
INNER JOIN ORDERDETAILS OD ON ITM.ID=OD.ITEMID
INNER JOIN ORDERS O ON O.ID= OD.ORDERID

GROUP BY ITM.CATEGORY1
ORDER BY SUM(OD.LINETOTAL) DESC

SELECT * FROM VW_TOP10_KATEGORI


-- BASKA BIR VIEW KULLANARAK YENI VIEW OLUSTURMA
CREATE VIEW TOP_10_KATEGORI_VIEW
AS
SELECT TOP 10 
CATEGORY1, SUM(SATIRTOPLAMI) TOPLAMTUTAR
FROM
VW_SIPARIS_DETAYLAR
GROUP BY CATEGORY1
ORDER BY SUM(SATIRTOPLAMI)DESC

--SELECT * FROM TOP_10_KATEGORI_VIEW
